language: python
services:
  - mongodb
  - redis-server
  - elasticsearch
matrix:
  include:
   - env: TOXENV=py27-dj17
     python: 2.7
   - env: TOXENV=pypy-dj17
     python: pypy
   - env: TOXENV=py34-dj17
     python: 3.4
   - env: TOXENV=py35-dj17
     python: 3.5
   - env: TOXENV=py27-dj18
     python: 2.7
   - env: TOXENV=pypy-dj18
     python: pypy
   - env: TOXENV=py34-dj18
     python: 3.4
   - env: TOXENV=py35-dj18
     python: 3.5
   - env: TOXENV=py27-dj19
     python: 2.7
   - env: TOXENV=pypy-dj19
     python: pypy
   - env: TOXENV=py34-dj19
     python: 3.4
   - env: TOXENV=py35-dj19
     python: 3.5
   - env: TOXENV=flake8
     python: 3.4
install:
  - pip install tox
script:
  - tox
