language: python
services:
  - mongodb
  - redis-server
  - elasticsearch
matrix:
  include:
   - env: TOXENV=py27-dj18
     python: 2.7
   - env: TOXENV=pypy-dj18
     python: pypy
   - env: TOXENV=py34-dj18
     python: 3.4
   - env: TOXENV=py35-dj18
     python: 3.5
   - env: TOXENV=py36-dj18
     python: 3.6
   - env: TOXENV=py27-dj19
     python: 2.7
   - env: TOXENV=pypy-dj19
     python: pypy
   - env: TOXENV=py34-dj19
     python: 3.4
   - env: TOXENV=py35-dj19
     python: 3.5
   - env: TOXENV=py36-dj19
     python: 3.6     
   - env: TOXENV=py27-dj110
     python: 2.7
   - env: TOXENV=pypy-dj110
     python: pypy
   - env: TOXENV=py34-dj110
     python: 3.4
   - env: TOXENV=py35-dj110
     python: 3.5
   - env: TOXENV=py36-dj110
     python: 3.6     
   - env: TOXENV=py27-dj111
     python: 2.7
   - env: TOXENV=pypy-dj111
     python: pypy
   - env: TOXENV=py34-dj111
     python: 3.4
   - env: TOXENV=py35-dj111
     python: 3.5
   - env: TOXENV=py36-dj111
     python: 3.6    
   - env: TOXENV=flake8
     python: 3.4
before_install:
   # RethinkDB
   - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
   - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
   # InfluxDB
   - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
   - source /etc/lsb-release
   - echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
   # Install both
   - sudo apt-get update
   - sudo apt-get install influxdb rethinkdb -y
install:
  - pip install tox
before_script:
  - rethinkdb --daemon
  - sudo service influxdb start
script:
  - tox
